apiVersion: networking.k8s.io/v1
kind: Ingress
annotations:
metadata:
  name: edu-sharing-connector-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  tls:
  - hosts:
    - connector.services.{{ .Values.baseUrl }}
    secretName: edu-sharing-connector-tls
  rules:
  - host: connector.services.{{ .Values.baseUrl }}
    http:
      paths:
      - backend:
          service:
            name: edu-sharing-connector
            port:
              number: 80
        path: /
        pathType: Prefix