apiVersion: networking.k8s.io/v1
kind: Ingress
annotations:
metadata:
  name: edu-sharing-connector-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ if .Values.absoluteUrl }}{{ .Values.absoluteUrl }}{{else}}"connector.services.{{ .Values.baseUrl }}"{{ end }}
    secretName: edu-sharing-connector-tls
  rules:
  - host: {{ if .Values.absoluteUrl }}{{ .Values.absoluteUrl }}{{else}}"connector.services.{{ .Values.baseUrl }}"{{ end }}
    http:
      paths:
      - backend:
          service:
            name: edu-sharing-connector
            port:
              number: 80
        path: /
        pathType: Prefix