apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edu-sharing-services-connector-data
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "30Gi"