# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:latest

# Select what we should cache between builds
cache:
  paths:
    - vendor/
    
stages:
  - deploy

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - echo "commit $CI_COMMIT_SHORT_SHA" > VERSION.md
  - rm -rf .git/


deploy_release:
  stage: deploy
  artifacts:
    name: "educonnector_release_${CI_COMMIT_SHORT_SHA}"
    paths:
      - ./
  script:
      - ls ./
