# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/

# Select what we should cache between builds
#cache:
#  paths:
#    - vendor/

stages:
  - test
  - deploy

php security audit errors:
  image:
    name: tophfr/phpcs-security-audit
    entrypoint: [""]
  script: /usr/local/bin/phpcs --standard=/usr/local/lib/composer/vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml -n .

php security audit warnings:
  image:
    name: tophfr/phpcs-security-audit
    entrypoint: [""]
  script: /usr/local/bin/phpcs --standard=/usr/local/lib/composer/vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml .
  allow_failure: true

deploy_release:
  image: php:latest
  stage: deploy
  artifacts:
    name: 'educonnector_release$(date +"%Y-%m-%d")${CI_COMMIT_SHORT_SHA}'
    paths:
      - ./
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - date=$(date --iso-8601=seconds)
    - sed -i "s/#BUILD_DATE/$date/g" install/version_info.php
    - sed -i "s/#BUILD_COMMIT/$CI_COMMIT_SHORT_SHA/g" install/version_info.php
    - sed -i "s/#BUILD_BRANCH/$CI_COMMIT_REF_NAME/g" install/version_info.php
  script:
    - rm -rf .git/
    - find ./vendor/ -name ".git" -exec rm -rf {} \; || true
    - ls ./
