# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/

# Select what we should cache between builds
#cache:
#  paths:
#    - vendor/

stages:
  - test
  - deploy

php security audit errors:
  image:
    name: tophfr/phpcs-security-audit
    entrypoint: [""]
  script: /usr/local/bin/phpcs --standard=/usr/local/lib/composer/vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml -n .

php security audit warnings:
  image:
    name: tophfr/phpcs-security-audit
    entrypoint: [""]
  script: /usr/local/bin/phpcs --standard=/usr/local/lib/composer/vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml .
  allow_failure: true

deploy_release:
  image: php:latest
  stage: deploy
  artifacts:
    name: "educonnector_release-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - date=$(date --iso-8601=seconds)
    - sed -i "s/#BUILD_DATE/$date/g" install/version_info.php
    - sed -i "s/#BUILD_COMMIT/$CI_COMMIT_SHORT_SHA/g" install/version_info.php
    - sed -i "s/#BUILD_BRANCH/$CI_COMMIT_REF_NAME/g" install/version_info.php
  script:
    - rm -rf .git/
    - find ./vendor/ -name ".git" -exec rm -rf {} \; || true
    - ls ./


build-docker:
  image: docker:20-dind
  stage: deploy
  services:
    - name: docker:20-dind
      alias: docker
      command: [ "--tls=false" ]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_REGISTRY/projects/community/edu_sharing-projects-community-deploy-docker-services-connector:$([[ $CI_COMMIT_REF_NAME = "main" ]] && echo "main" || echo "dev") .
    - docker push $DOCKER_REGISTRY/projects/community/edu_sharing-projects-community-deploy-docker-services-connector:$([[ $CI_COMMIT_REF_NAME = "main" ]] && echo "main" || echo "dev")

