version: "3.9"

services:
  edu-connector-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'connector'
      MYSQL_USER: 'connector'
      MYSQL_PASSWORD: 'connector'
      MYSQL_ROOT_PASSWORD: 'connector'
    volumes:
      - db:/var/lib/mysql
    networks:
      - connector

  edu-connector:
    image: edu_sharing-community-services-connector:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WWW_URL: http://localhost:80
      DATABASE_HOST: edu-connector-db
      DATABASE_PORT: 3306
      DATABASE_NAME: connector
      DATABASE_USER: connector
      DATABASE_PASSWORD: connector
    volumes:
      - data:/var/www/html/data
    networks:
      - connector
      - edu-sharing
    ports:
      - "80:80"

  edu-connector-init:
    image: edu_sharing-community-services-connector:dev
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["init.sh"]
    environment:
      DEBUG: true
      CONNECTOR_INTERNAL_HOST: edu-connector
      CONNECTOR_INTERNAL_PORT: "80"
      REPOSITORY_SERVICE_PROT: "http"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_PATH: "/edu-sharing"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
    depends_on:
      - edu-connector
    networks:
      - edu-sharing

networks:
  edu-connector:
  edu-sharing:
    external:
      name: ${EDU_SHARING_NETWORK:-edu-sharing_default}

volumes:
  db:
  data: