baseUrl: 
storageClassName:
clusterIssuer: letsencrypt
version: ${docker.tag}
database:
  storageSize: 30Gi
  enabled: true
  # when enabled = false for external database
  config:
    host: "???"
    port: "???"
    database: "???"
    username: "???"
    password: "???"
  podSecurityContext:
    fsGroup: 1001
  securityContext:
    runAsUser: 1001
config:
  cache:
    ## @param config.cache.cluster Set cache as cluster
    cluster: true
    ## @param config.cache.database Set cache database
    database: 1
    ## @param config.cache.host Set cache host
    host: edusharing-rediscluster
    ## @param config.cache.port Set cache port
    port: 6379

onlyofficeDocumentServer:
# enable the save button in only office
onlyofficeForceSaveEnabled: false
onlyofficePluginUrl:
onlyOfficePlugins: true

onlyofficeEdusharingPlugin:
  enabled: false
  label:
  url:

global:
  image:
    pullSecret:
    registry: docker.edu-sharing.com
    pullPolicy: Always
image:
  custom:
    postgresql: ${docker.edu_sharing.community.common.postgresql}

podSecurityContext:

  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1000

ingress:
  annotations:
