version: "3.9"

services:
  services-edu-connector-database:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-mysql:${docker.tag}"
    container_name: "services-edu-connector-database_${COMPOSE_PROJECT_NAME}"
    environment:
      MYSQL_USER: "${SERVICES_EDU_CONNECTOR_DATABASE_USER:-connector}"
      MYSQL_PASSWORD: "${SERVICES_EDU_CONNECTOR_DATABASE_PASS:-connector}"
      MYSQL_DATABASE: "${SERVICES_EDU_CONNECTOR_DATABASE_NAME:-connector}"
      MYSQL_ROOT_PASSWORD: "${SERVICES_EDU_CONNECTOR_DATABASE_ROOT_PASS:-connector}"
    volumes:
      - services-edu-connector-database-data:/bitnami/mysql/data

  services-edu-connector-service:
    image: "${docker.repository}/${docker.prefix}-service:${docker.tag}"
    container_name: "services-edu-connector-service_${COMPOSE_PROJECT_NAME}"
    environment:
      PROT_EXTERNAL: "${SERVICES_EDU_CONNECTOR_PROT_EXTERNAL:-http}"
      HOST_EXTERNAL: "${SERVICES_EDU_CONNECTOR_HOST_EXTERNAL:-edu.connector.127.0.0.1.nip.io}"
      PORT_EXTERNAL: "${SERVICES_EDU_CONNECTOR_PORT_EXTERNAL:-9200}"
      PATH_EXTERNAL: "${SERVICES_EDU_CONNECTOR_PATH_EXTERNAL:-}"
      DATABASE_HOST: services-edu-connector-database
      DATABASE_PORT: "3306"
      DATABASE_NAME: "${SERVICES_EDU_CONNECTOR_DATABASE_NAME:-connector}"
      DATABASE_USER: "${SERVICES_EDU_CONNECTOR_DATABASE_USER:-connector}"
      DATABASE_PASSWORD: "${SERVICES_EDU_CONNECTOR_DATABASE_PASS:-connector}"
    volumes:
      - "services-edu-connector-data:/var/data"
    depends_on:
      - services-edu-connector-database
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${SERVICES_EDU_CONNECTOR_PORT_HTTP:-9200}:80"

  services-edu-connector-service-init:
    image: "${docker.repository}/${docker.prefix}-service:${docker.tag}"
    container_name: "services-edu-connector-service-init_${COMPOSE_PROJECT_NAME}"
    entrypoint: ["init.sh"]
    environment:
      DEBUG: true
      CONNECTOR_INTERNAL_HOST: services-edu-connector
      CONNECTOR_INTERNAL_PORT: "80"
      REPOSITORY_SERVICE_PROT: "http"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_PATH: "/edu-sharing"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
    depends_on:
      - services-edu-connector-service

volumes:
  services-edu-connector-database-data:
  services-edu-connector-data: