version: "3.9"

services:

  services-connector-database:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.postgresql.name}:${docker.edu_sharing.community.common.postgresql.tag}"
    container_name: "services-connector-database_${COMPOSE_PROJECT_NAME}"
    environment:
      POSTGRESQL_DATABASE: "${SERVICES_CONNECTOR_DATABASE_NAME:-connector}"
      POSTGRESQL_POSTGRES_PASSWORD: "${SERVICES_CONNECTOR_DATABASE_PASS:-connector}"
      POSTGRESQL_PASSWORD: "${SERVICES_CONNECTOR_DATABASE_PASS:-connector}"
      POSTGRESQL_USERNAME: "${SERVICES_CONNECTOR_DATABASE_USER:-connector}"
    expose:
      - "5432"
    shm_size: 256m
    volumes:
      - "services-connector-database-volume-data:/bitnami/postgresql"

  services-connector-service:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-service:${docker.tag}"
    container_name: "services-connector-service_${COMPOSE_PROJECT_NAME}"
    environment:
      SERVICES_CONNECTOR_SERVICE_PROT_EXTERNAL: "${SERVICES_CONNECTOR_SERVICE_PROT_EXTERNAL:-http}"
      SERVICES_CONNECTOR_SERVICE_HOST_EXTERNAL: "${SERVICES_CONNECTOR_SERVICE_HOST_EXTERNAL:-connector.services.127.0.0.1.nip.io}"
      SERVICES_CONNECTOR_SERVICE_PORT_EXTERNAL: "${SERVICES_CONNECTOR_SERVICE_PORT_EXTERNAL:-9300}"
      SERVICES_CONNECTOR_SERVICE_PATH_EXTERNAL: "${SERVICES_CONNECTOR_SERVICE_PATH_EXTERNAL:-}"
      SERVICES_CONNECTOR_SERVICE_HOST_ALIASES: "${SERVICES_CONNECTOR_SERVICE_HOST_ALIASES:-}"
      SERVICES_CONNECTOR_SERVICE_HOST_ALLOW_INTERNAL_IP: "${SERVICES_CONNECTOR_SERVICE_HOST_ALLOW_INTERNAL_IP:-false}"
      SERVICES_CONNECTOR_DATABASE_HOST: services-connector-database
      SERVICES_CONNECTOR_DATABASE_PORT: "5432"
      SERVICES_CONNECTOR_DATABASE_NAME: "${SERVICES_CONNECTOR_DATABASE_NAME:-connector}"
      SERVICES_CONNECTOR_DATABASE_USER: "${SERVICES_CONNECTOR_DATABASE_USER:-connector}"
      SERVICES_CONNECTOR_DATABASE_PASS: "${SERVICES_CONNECTOR_DATABASE_PASS:-connector}"
      SERVICES_CONNECTOR_ONLYOFFICE_DOCUMENT_SERVER: "${SERVICES_CONNECTOR_ONLYOFFICE_DOCUMENT_SERVER:-}"
      SERVICES_CONNECTOR_ONLYOFFICE_PLUGINS: "${SERVICES_CONNECTOR_ONLYOFFICE_PLUGINS:-true}"
      SERVICES_CONNECTOR_ONLYOFFICE_FORCE_SAVE_ENABLED: "${SERVICES_CONNECTOR_ONLYOFFICE_FORCE_SAVE_ENABLED:-false}"
      SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN: "${SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN:-false}"
      SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN_LABEL: "${SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN_LABEL:-}"
      SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN_ICON: "${SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN_ICON:-}"
      SERVICES_CONNECTOR_ONLYOFFICE_JWT_SECRET: "${SERVICES_CONNECTOR_ONLYOFFICE_JWT_SECRET:-}"
      SERVICES_CONNECTOR_H5P_SUPPRESS_CLEANUP: "${SERVICES_CONNECTOR_H5P_SUPPRESS_CLEANUP:-false}"
      SERVICES_CONNECTOR_SERVICE_UPLOAD_FILE_SIZE: "${SERVICES_CONNECTOR_SERVICE_UPLOAD_FILE_SIZE:-512M}"
      SERVICES_CONNECTOR_SERVICE_POST_MAX_SIZE: "${SERVICES_CONNECTOR_SERVICE_POST_MAX_SIZE:-513M}"
      SERVICES_CONNECTOR_SERVICE_MEMORY_LIMIT: "${SERVICES_CONNECTOR_SERVICE_MEMORY_LIMIT:-1024M}"
    expose:
      - "8080"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${SERVICES_CONNECTOR_SERVICE_PORT:-9300}:8081"
    volumes:
      - "services-connector-service-volume-data:/var/data"
    depends_on:
      - services-connector-database

  services-connector-service-init:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-service:${docker.tag}"
    container_name: "services-connector-service-init_${COMPOSE_PROJECT_NAME}"
    entrypoint: ["init.sh"]
    environment:
      SERVICES_CONNECTOR_SERVICE_HOST_INTERNAL: services-connector-service
      SERVICES_CONNECTOR_SERVICE_PORT_INTERNAL: "8080"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
    depends_on:
      - services-connector-service

volumes:
  services-connector-database-volume-data:
  services-connector-service-volume-data:
