version: "3.9"

services:
  services-edu-connector-database:
    image: "${docker.edu_sharing.community.common.postgresql}"
    container_name: "services-edu-connector-database_${COMPOSE_PROJECT_NAME}"
    environment:
      POSTGRESQL_USERNAME: "${SERVICES_EDU_CONNECTOR_DATABASE_USER:-connector}"
      POSTGRESQL_POSTGRES_PASSWORD: "${SERVICES_EDU_CONNECTOR_DATABASE_PASS:-connector}"
      POSTGRESQL_DATABASE: "${SERVICES_EDU_CONNECTOR_DATABASE_NAME:-connector}"
      POSTGRESQL_PASSWORD: "${SERVICES_EDU_CONNECTOR_DATABASE_ROOT_PASS:-connector}"
    volumes:
      - "services-edu-connector-database-data:/bitnami/postgresql"

  services-edu-connector-service:
    image: "${docker.repository}/${docker.prefix}-service:${docker.tag}"
    container_name: "services-edu-connector-service_${COMPOSE_PROJECT_NAME}"
    environment:
      PROT_EXTERNAL: "${SERVICES_EDU_CONNECTOR_PROT_EXTERNAL:-http}"
      HOST_EXTERNAL: "${SERVICES_EDU_CONNECTOR_HOST_EXTERNAL:-edu.connector.127.0.0.1.nip.io}"
      PORT_EXTERNAL: "${SERVICES_EDU_CONNECTOR_PORT_EXTERNAL:-9200}"
      PATH_EXTERNAL: "${SERVICES_EDU_CONNECTOR_PATH_EXTERNAL:-}"
      DATABASE_TYPE: pgsql
      DATABASE_HOST: services-edu-connector-database
      DATABASE_PORT: "5432"
      DATABASE_NAME: "${SERVICES_EDU_CONNECTOR_DATABASE_NAME:-connector}"
      DATABASE_USER: "${SERVICES_EDU_CONNECTOR_DATABASE_USER:-connector}"
      DATABASE_PASSWORD: "${SERVICES_EDU_CONNECTOR_DATABASE_PASS:-connector}"
      ONLYOFFICE_DOCUMENT_SERVER: "${SERVICES_EDU_CONNECTOR_ONLYOFFICE_DOCUMENT_SERVER:-}"
      ONLYOFFICE_PLUGIN_URL: "${SERVICES_EDU_CONNECTOR_ONLYOFFICE_PLUGIN_URL:-}"
      ONLYOFFICE_JWT_SECRET: "${SERVICES_EDU_CONNECTOR_ONLYOFFICE_JWT_SECRET:-}"
      MOODLE_BASE_DIR: "${SERVICES_EDU_CONNECTOR_MOODLE_BASE_DIR:-}"
      MOODLE_TOKEN: "${SERVICES_EDU_CONNECTOR_MOODLE_TOKEN:-}"
    volumes:
      - "services-edu-connector-data:/var/data"
    depends_on:
      - services-edu-connector-database
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${SERVICES_EDU_CONNECTOR_PORT_HTTP:-9200}:80"

  services-edu-connector-service-init:
    image: "${docker.repository}/${docker.prefix}-service:${docker.tag}"
    container_name: "services-edu-connector-service-init_${COMPOSE_PROJECT_NAME}"
    entrypoint: ["init.sh"]
    environment:
      DEBUG: true
      CONNECTOR_INTERNAL_HOST: services-edu-connector-service
      CONNECTOR_INTERNAL_PORT: "80"
      REPOSITORY_SERVICE_PROT: "http"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_PATH: "/edu-sharing"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
    depends_on:
      - services-edu-connector-service

volumes:
  services-edu-connector-database-data:
  services-edu-connector-data: