apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
data:
  CACHE_CLUSTER: {{ .Values.config.cache.cluster | quote }}
  CACHE_DATABASE: {{ .Values.config.cache.database | quote }}
  CACHE_HOST: {{ .Values.config.cache.host | quote }}
  CACHE_PORT: {{ .Values.config.cache.port | quote }}
  REPOSITORY_SERVICE_HOST: {{ .Values.config.repository.host | quote }}
  REPOSITORY_SERVICE_PORT: {{ .Values.config.repository.port | quote }}
  SERVICES_CONNECTOR_REPOSITORY_FORCE_INTERN_COM: {{ .Values.config.repository.forceInternalCommunication | quote }}
  SERVICES_CONNECTOR_REPOSITORY_FORCED_APIURL: {{ .Values.config.repository.apiUrl | quote }}
  SERVICES_CONNECTOR_DATABASE_HOST: {{ .Values.config.database.host | quote }}
  SERVICES_CONNECTOR_DATABASE_NAME: {{ .Values.config.database.database | quote }}
  SERVICES_CONNECTOR_DATABASE_PORT: {{ .Values.config.database.port | quote }}
  SERVICES_CONNECTOR_ONLYOFFICE_DOCUMENT_SERVER: {{ .Values.config.onlyoffice.server.url | quote }}
  SERVICES_CONNECTOR_ONLYOFFICE_PLUGINS: {{ .Values.config.onlyoffice.editor.embedRepo | quote }}
  SERVICES_CONNECTOR_ONLYOFFICE_FORCE_SAVE_ENABLED: {{ .Values.config.onlyoffice.editor.forceSave | quote }}
  SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN: {{ .Values.config.onlyoffice.plugin.enabled | quote }}
  SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN_LABEL: {{ .Values.config.onlyoffice.plugin.label | quote }}
  SERVICES_CONNECTOR_ONLYOFFICE_EDUSHARING_PLUGIN_ICON: {{ .Values.config.onlyoffice.plugin.icon | quote }}
  SERVICES_CONNECTOR_H5P_SUPPRESS_CLEANUP: {{ .Values.config.h5p.cache.suppressCleanup | quote }}
  SERVICES_CONNECTOR_SERVICE_HOST_EXTERNAL: {{ .Values.ingress.hosts | first | quote }}
  SERVICES_CONNECTOR_SERVICE_HOST_INTERNAL: {{ include "edusharing_common_lib.names.name" . | quote }}
  {{- with .Values.config.server.host.aliases }}
  SERVICES_CONNECTOR_SERVICE_HOST_ALIASES: '{{- join "," . }}'
  {{- end }}
  SERVICES_CONNECTOR_SERVICE_HOST_ALLOW_INTERNAL_IP: {{ .Values.config.server.host.allowInternalIp | quote }}
  SERVICES_CONNECTOR_SERVICE_MEMORY_LIMIT: {{ .Values.config.server.memoryLimit | quote }}
  SERVICES_CONNECTOR_SERVICE_PATH_EXTERNAL: {{ if eq (.Values.ingress.paths | first) "/" -}}{{ "" | quote }}{{- else -}}{{ .Values.ingress.paths | first | quote }}{{- end }}
  SERVICES_CONNECTOR_SERVICE_PORT_EXTERNAL: {{ if .Values.ingress.tls }}"443"{{ else }}"80"{{ end }}
  SERVICES_CONNECTOR_SERVICE_PORT_INTERNAL: {{ .Values.service.port.api.internal | quote }}
  SERVICES_CONNECTOR_SERVICE_POST_MAX_SIZE: {{ .Values.config.server.postMaxSize | quote }}
  SERVICES_CONNECTOR_SERVICE_PROT_EXTERNAL: {{ if .Values.ingress.tls }}"https"{{ else }}"http"{{ end }}
  SERVICES_CONNECTOR_SERVICE_UPLOAD_FILE_SIZE: {{ .Values.config.server.uploadFileSizeLimit | quote }}
