apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
type: Opaque
data:
  REPOSITORY_SERVICE_ADMIN_PASS: {{ default .Values.global.password .Values.config.repository.password | b64enc | quote }}
  SERVICES_CONNECTOR_DATABASE_USER: {{ .Values.config.database.username | b64enc | quote }}
  SERVICES_CONNECTOR_DATABASE_PASS: {{ default .Values.global.password .Values.config.database.password | b64enc | quote }}
  {{- with .Values.config.onlyoffice.server.jwtSecret }}
  SERVICES_CONNECTOR_ONLYOFFICE_JWT_SECRET: {{ . | b64enc | quote }}
  {{- end }}
