version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'connector'
      MYSQL_USER: 'connector'
      MYSQL_PASSWORD: 'connector'
      MYSQL_ROOT_PASSWORD: 'connector'
    volumes:
      - db:/var/lib/mysql
    networks:
      - connector
  connector:
    image: connector:latest
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      WWWURL: http://localhost:8082/eduConnector
      DBHOST: http://db:9200
      DBUSER: connector
      DBNAME: connector
      DBPASSWORD: connector
    volumes:
      - data:/var/www/html/data
    networks:
      - connector
    ports:
      - "8082:80"

networks:
  connector:

volumes:
  db:
  data: