version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'connector'
      MYSQL_USER: 'connector'
      MYSQL_PASSWORD: 'connector'
      MYSQL_ROOT_PASSWORD: 'connector'
    volumes:
      - db:/var/lib/mysql
    networks:
      - connector
  connector:
    image: connector:latest
    build:
      context: ../
      dockerfile: .legacy/Dockerfile

    volumes:
      - ../:/var/www/html
    networks:
      - connector
    ports:
      - "8082:80"

networks:
  connector:

volumes:
  db: