baseUrl: 
storageClassName:
clusterIssuer: letsencrypt
version: maven-fixes-9.0-SNAPSHOT
database:
  storageSize: 30Gi
  enabled: true
  # when enabled = false for external database
  config:
    host: "???"
    port: "???"
    database: "???"
    username: "???"
    password: "???"
  podSecurityContext:
    fsGroup: 1001
  securityContext:
    runAsUser: 1001

images:
  postgresql: docker.edu-sharing.com/community/common/edu_sharing-community-common-docker-postgresql:13.15.0

podSecurityContext:

  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1000

ingress:
  annotations:
