baseUrl: 
storageClassName:
clusterIssuer: letsencrypt
version: 8.1.2
database:
  storageSize: 30Gi
  enabled: true
  # when enabled = false for external database
  config:
     host: "???"
     port: "???"
     database: "???"
     username: "???"
     password: "???"