<html>
    <head>
        <link rel="stylesheet" href="<?php echo WWWROOT ?>/css/screen.css">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
		<meta charset="utf-8"/>
		<title>edu-sharing Etherpad Konnektor</title>
    </head>
    <body>
        <div id="topbar"><h1>edu-sharing Etherpad Konnektor</h1></div>
        <div id="content">
        	<p>Geben Sie einen Namen für das Etherpad ein und klicken Sie auf "Pad instanziieren."<br/>
        	Nach der Instanziierung werden Sie automatisch zum Etherpad weitergeleitet.</p>
            <form id="etherpadForm" action="?" method="get">
                <input type="hidden" name="tool" value="edu-tool-etherpad">
                <input name="title" placeholder="Padname (gültiger Dateiname)">
                <a class="submit" href="#" onclick="document.getElementById('etherpadForm').submit();">Pad instanziieren</a>
            </form>
        </div>
    </body>
</html>
