<html>
    <head>
        <link rel="stylesheet" href="<?php echo WWWROOT ?>/css/screen.css">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
		<meta charset="utf-8"/>
        <title>edu-sharing Moodle Konnektor</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script src="<?php echo WWWROOT ?>/js/moodle.js"></script>
    </head>
    <body>
        <div id="topbar"><h1>edu-sharing Moodle Konnektor</h1></div>
        <div id="content">
            <p>Geben Sie einen Kursnamen ein, wählen Sie eine Kategorie und klicken Sie auf "Kurs instanziieren."<br/>
            Nach der Instanziierung werden Sie automatisch zum neuen Kurs weitergeleitet.<br/>
            Das Moodle-Zielsystem ist <a href="<?php echo MOODLEURL ?>" target="_blank"><?php echo MOODLEURL ?>.</a></p>
            <!-- <div class="clt"><?php $this -> renderCategories() ?></div> -->
            <form id="moodleForm" action="?" method="get">
                <input type="hidden" name="tool" value="MOODLE">
                <input type="hidden" name="import" value="yes">
                <input type="hidden" name="categoryid" value="">
                <input type="hidden" name="nodeid" value="<?php echo $this -> nodeId ?>">
                <input id="title" name="title" placeholder="Kursname (gültiger Dateiname)">
                <a class="submit" href="#" onclick="document.getElementById('moodleForm').submit();">Kurs instanziieren</a>
            </form>
            <?php $this -> renderCategories() ?>
        </div>
    </body>
</html>
