<html>
    <head>
        <link rel="stylesheet" href="<?php echo WWWROOT ?>/css/screen.css">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
		<meta charset="utf-8"/>
		<title>edu-sharing OnlyOffice Konnektor</title>
    </head>
    <body>
        <div id="topbar"><h1>edu-sharing OnlyOffice Konnektor</h1></div>
        <div id="content">
        	<p>Wählen Sie den Dokumenttyp und geben Sie einen Namen für das Dokument ein. Klicken Sie anschließend auf "Dokument erstellen."</p>
            <form id="onlyofficeForm" action="?" method="get">
                <input type="hidden" name="tool" value="ONLY_OFFICE">
				<input type="hidden" name="createdocument" value="yes">
				<select id="doctype" name="tool_subtype">
					<option value="docx">Textdokument (*.docx)</option>
					<option value="odt">Textdokument (*.odt)</option>
					<option value="xlsx">Tabellenmappe (*.xlsx)</option>
					<option value="ods">Tabellenmappe (*.ods)</option>
					<option value="pptx">Präsentation (*.pptx)</option>
					<option value="odp">Präsentation (*.odp)</option>
				</select>
                <input name="title" placeholder="Dokumentname (gültiger Dateiname)">
                <a class="submit" href="#" onclick="document.getElementById('onlyofficeForm').submit();">Dokument erstellen</a>
            </form>
        </div>
    </body>
</html>